export const externalFields = [
  "location",
  "blastCode",
  "designHoles",
  "realHoles",
  "totalRealDrilledMeters",
  "designEmulsion",
  "realEmulsion",
  "p337",
  "ikon15m",
  "lastSyncedAt",
];

export const editableFields = [
  "subLocation",
  "date",
  "blastArea",
  "seamArea",
  "designBurden",
  "designSpacing",
  "designAverageLength",
  "omcAverageLength",
  "omcCoalCubicMeters",
  "omcTotalCubicMeters",
  "notes",
];

export const calculatedFields = [
  "period",
  "sterileArea",
  "designAreaPerHole",
  "realAreaPerHole",
  "holeAreaDifference",
  "blastAreaDifference",
  "realAverageLength",
  "averageLengthDifference",
  "totalDesignDrilledMeters",
  "drilledMetersDifference",
  "designBlastVolumeWithoutSeams",
  "realBlastVolumeWithoutSeams",
  "aycOmcDifference",
  "omcSterileCubicMeters",
  "omcSterileChargeFactor",
  "omcAycTotalVolumeDifference",
  "opitBlastChargeFactor",
  "realAycChargeFactor",
  "createdAt",
  "updatedAt",
  "closedAt",
  "status",
];

export const visibleBlastFields = [
  "location",
  "subLocation",
  "date",
  "period",
  "status",
  "blastCode",
  "blastArea",
  "seamArea",
  "sterileArea",
  "designHoles",
  "realHoles",
  "designBurden",
  "designSpacing",
  "designAreaPerHole",
  "realAreaPerHole",
  "holeAreaDifference",
  "blastAreaDifference",
  "designAverageLength",
  "realAverageLength",
  "averageLengthDifference",
  "totalDesignDrilledMeters",
  "totalRealDrilledMeters",
  "drilledMetersDifference",
  "designBlastVolumeWithoutSeams",
  "realBlastVolumeWithoutSeams",
  "designEmulsion",
  "p337",
  "ikon15m",
  "realEmulsion",
  "omcAverageLength",
  "aycOmcDifference",
  "omcSterileCubicMeters",
  "omcCoalCubicMeters",
  "omcTotalCubicMeters",
  "omcSterileChargeFactor",
  "omcAycTotalVolumeDifference",
  "opitBlastChargeFactor",
  "realAycChargeFactor",
  "lastSyncedAt",
  "closedAt",
  "notes",
  "createdAt",
  "updatedAt",
];

export const fieldLabels = {
  location: "Ubicacion",
  subLocation: "Sububicacion",
  date: "Fecha",
  period: "Periodo",
  status: "Estado",
  blastCode: "Voladura",
  blastArea: "Area vol.",
  seamArea: "Area manto",
  sterileArea: "Area esteril",
  designHoles: "Huecos dis.",
  realHoles: "Huecos real",
  designBurden: "Burden",
  designSpacing: "Espaciamiento",
  designAreaPerHole: "Area/h dis.",
  realAreaPerHole: "Area/h real",
  holeAreaDifference: "Dif. area/h",
  blastAreaDifference: "Dif. area vol.",
  designAverageLength: "Long. dis. prom.",
  realAverageLength: "Long. real prom.",
  averageLengthDifference: "Dif. long.",
  totalDesignDrilledMeters: "M dis. perf.",
  totalRealDrilledMeters: "M real perf.",
  drilledMetersDifference: "Dif. metros",
  designBlastVolumeWithoutSeams: "Vol. dis. sin manto",
  realBlastVolumeWithoutSeams: "Vol. real sin manto",
  designEmulsion: "Emulsion dis.",
  p337: "P337",
  ikon15m: "IKON 15M",
  realEmulsion: "Emulsion real",
  omcAverageLength: "Long. OMC prom.",
  aycOmcDifference: "Dif. AYC/OMC",
  omcSterileCubicMeters: "OMC m3 esteril",
  omcCoalCubicMeters: "OMC m3 carbon",
  omcTotalCubicMeters: "OMC m3 total",
  omcSterileChargeFactor: "FC esteril OMC",
  omcAycTotalVolumeDifference: "Dif. vol. AYC/OMC",
  opitBlastChargeFactor: "FC OPIT",
  realAycChargeFactor: "FC real AYC",
  lastSyncedAt: "Ultima sync",
  closedAt: "Cierre",
  notes: "Notas",
  createdAt: "Creado",
  updatedAt: "Actualizado",
};

export function isEditableField(field) {
  return editableFields.includes(field);
}
